### ISSUE TITLE
Database schemas

### ISSUE THREAD

**Issue by danog** [nebulaim/telegramd#6]
Hi there.
Thank you for this awesome project.
I have managed to run it however I couldn't find the mysql database scheme.
Any pointers?

**Comment by LoveYugui** [comment]
Our mistake! We forgot upload the schema file, just wait a minute so that someone will fix this mistake :)




| |
尤金朋
|
|
邮箱：youjinpeng_hdu@163.com
|

签名由 网易邮箱大师 定制

On 12/15/2017 21:18, Daniil Gentili wrote:

Hi there.
Thank you for this awesome project.
I have managed to run it however I couldn't find the mysql database scheme.
Any pointers?

**Comment by danog** [comment]
Thank you for the prompt response, everything works now (except for PFS, but I'm going to implement it as soon as I grasp the basics of your database API)
